
package com.jpl.garage.cxf.obsp;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-26T00:16:18.580+09:00
 * Generated source version: 2.7.4
 * 
 */
 
public class ObspInfo_ObspInfoPort_Server{

    protected ObspInfo_ObspInfoPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ObspInfoImpl();
        String address = "http://localhost:8100/cxf/Obsp";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ObspInfo_ObspInfoPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
