package com.jpl.garage.cxf.obsp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-26T00:16:18.539+09:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://www.cxf.garage.jpl.com/Obsp/", name = "ObspInfo")
@XmlSeeAlso({ObjectFactory.class})
public interface ObspInfo {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://www.cxf.garage.jpl.com/Obsp/", className = "com.jpl.garage.cxf.obsp.Service")
    @WebMethod(action = "http://www.cxf.garage.jpl.com/Obsp/service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://www.cxf.garage.jpl.com/Obsp/", className = "com.jpl.garage.cxf.obsp.ServiceResponse")
    public java.lang.String service(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
