package com.jpl.garage.cxf.obsp;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-26T00:16:18.586+09:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "ObspInfo", 
                  wsdlLocation = "src/main/resources/wsdls/Obsp.wsdl",
                  targetNamespace = "http://www.cxf.garage.jpl.com/Obsp/") 
public class ObspInfo_Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cxf.garage.jpl.com/Obsp/", "ObspInfo");
    public final static QName ObspInfoPort = new QName("http://www.cxf.garage.jpl.com/Obsp/", "ObspInfoPort");
    static {
        URL url = ObspInfo_Service.class.getResource("src/main/resources/wsdls/Obsp.wsdl");
        if (url == null) {
            url = ObspInfo_Service.class.getClassLoader().getResource("src/main/resources/wsdls/Obsp.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(ObspInfo_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/main/resources/wsdls/Obsp.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ObspInfo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ObspInfo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObspInfo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ObspInfo_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ObspInfo_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ObspInfo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ObspInfo
     */
    @WebEndpoint(name = "ObspInfoPort")
    public ObspInfo getObspInfoPort() {
        return super.getPort(ObspInfoPort, ObspInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObspInfo
     */
    @WebEndpoint(name = "ObspInfoPort")
    public ObspInfo getObspInfoPort(WebServiceFeature... features) {
        return super.getPort(ObspInfoPort, ObspInfo.class, features);
    }

}
