DROP TABLE BBS_COMMENT;
CREATE TABLE BBS_COMMENT (
 	S_BBS_ID VARCHAR2(50),
	I_BBS_IDX INTEGER,
	I_COMMENT_IDX INTEGER,
	S_COMMENT VARCHAR2(2000),
	PRIMARY KEY(S_BBS_ID,I_BBS_IDX,I_COMMENT_IDX)
);

INSERT INTO "PUBLIC"."BBS_COMMENT" VALUES ('1', 1, 1, 'cmt_1');
INSERT INTO "PUBLIC"."BBS_COMMENT" VALUES ('1', 1, 2, 'cmt_2');
INSERT INTO "PUBLIC"."BBS_COMMENT" VALUES ('1', 1, 3, 'cmt_3');
