CREATE TABLE BBS_DATA(
	S_BBS_ID VARCHAR2(50),
	I_BBS_IDX INTEGER,
	I_PARENT_IDX INTEGER,
	I_IDX_LEFT INTEGER,
	I_IDX_RIGHT INTEGER,
	S_BBS_TITLE VARCHAR2(2000),
	S_BBS_DESC VARCHAR2(2000),
	PRIMARY KEY(S_BBS_ID,I_BBS_IDX)
);

INSERT INTO "PUBLIC"."BBS_DATA" ("S_BBS_ID", "I_BBS_IDX", "I_PARENT_IDX", "I_IDX_LEFT", "I_IDX_RIGHT", "S_BBS_TITLE", "S_BBS_DESC") 
VALUES ('1', 1, 0, NULL, NULL, 'help_1', 'help_desc');
INSERT INTO "PUBLIC"."BBS_DATA" ("S_BBS_ID", "I_BBS_IDX", "I_PARENT_IDX", "I_IDX_LEFT", "I_IDX_RIGHT", "S_BBS_TITLE", "S_BBS_DESC") 
VALUES ('1', 2, 0, NULL, NULL, 'help_2', 'help_desc');
INSERT INTO "PUBLIC"."BBS_DATA" ("S_BBS_ID", "I_BBS_IDX", "I_PARENT_IDX", "I_IDX_LEFT", "I_IDX_RIGHT", "S_BBS_TITLE", "S_BBS_DESC") 
VALUES ('2', 1, 0, NULL, NULL, 'qna_1', 'qna_desc');
