DROP TABLE BBS_INFO;
CREATE TABLE BBS_INFO(
	S_BBS_ID VARCHAR2(50) PRIMARY KEY,
	S_BBS_NAME VARCHAR2(50),
	C_BBS_TYPE CHAR(1),
	C_USE_YN CHAR(1),
	C_EMAIL_YN CHAR(1),
	C_NOTICE_YN CHAR(1),
	I_HOT_ICON_COUNT INTEGER,
	I_NEW_ICON_DAY INTEGER,
	C_POPUP_YN CHAR(1),
	C_OPEN_YN CHAR(1),
	C_VOTE_YN CHAR(1),
	C_REPLY_YN CHAR(1),
	C_COMMENT_YN CHAR(1),
	C_HTML_YN CHAR(1),
	C_WASTE_YN CHAR(1),
	S_DATE_FORMAT VARCHAR2(20),
	I_LIST_COUNT INTEGER,
	I_FILE_COUNT INTEGER,
	I_FILE_SIZE INTEGER,
	S_HEADER VARCHAR2(2000),
	S_HEAD_DESC VARCHAR2(2000),
	S_TAIL_DESC VARCHAR2(2000),
	D_CREATE TIMESTAMP
);

INSERT INTO "PUBLIC"."BBS_INFO" ("S_BBS_ID", "S_BBS_NAME", "C_BBS_TYPE", "C_USE_YN", "C_EMAIL_YN", "C_NOTICE_YN", "I_HOT_ICON_COUNT", "I_NEW_ICON_DAY", "C_POPUP_YN", "C_OPEN_YN", "C_VOTE_YN", "C_REPLY_YN", "C_COMMENT_YN", "C_HTML_YN", "C_WASTE_YN", "S_DATE_FORMAT", "I_LIST_COUNT", "I_FILE_COUNT", "I_FILE_SIZE", "S_HEADER", "S_HEAD_DESC", "S_TAIL_DESC", "D_CREATE")
VALUES ('1', 'help', 'N', 'Y', 'N', 'N', 0, 0, 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'yyyy/MM/dd', 10, 10, 100, NULL, NULL, NULL, '2011-10-30 01:02:06');
INSERT INTO "PUBLIC"."BBS_INFO" ("S_BBS_ID", "S_BBS_NAME", "C_BBS_TYPE", "C_USE_YN", "C_EMAIL_YN", "C_NOTICE_YN", "I_HOT_ICON_COUNT", "I_NEW_ICON_DAY", "C_POPUP_YN", "C_OPEN_YN", "C_VOTE_YN", "C_REPLY_YN", "C_COMMENT_YN", "C_HTML_YN", "C_WASTE_YN", "S_DATE_FORMAT", "I_LIST_COUNT", "I_FILE_COUNT", "I_FILE_SIZE", "S_HEADER", "S_HEAD_DESC", "S_TAIL_DESC", "D_CREATE")
VALUES ('2', 'qna', 'N', 'Y', 'N', 'N', 0, 0, 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'yyyy/MM/dd', 10, 10, 100, NULL, NULL, NULL, '2011-10-30 01:02:15');
